### ISSUE TITLE
Sponge Version API

### ISSUE THREAD

**Issue by phase** [SpongePowered/SpongeWebAPI#2]
Ore needs a mapping from Sponge API Version to Minecraft Version. i.e. "Sponge API 8 works on 1.13 and 1.14" or whatever. This map should also work in reverse, and should accept snapshot mappings like `Sponge-8.0.0-githashhere`.

**Comment by Minecrell** [comment]
See https://github.com/SpongePowered/DownloadIndexer/issues/7

**Comment by phase** [comment]
Why not have this as a common Web API that both _Downloads_ and _Ore_ use? It seems silly to have two sources of information.

**Comment by Minecrell** [comment]
@phase Well, my plan is to have the downloads API provide this information. Not sure why there would be two sources of information.

**Comment by phase** [comment]
If Downloads has the version API, then _SpongeWebAPI_ and _Downloads_ are providing their own APIs. The whole point of this repo is to consolidate the APIs.

**Comment by Minecrell** [comment]
@phase I'm afraid I don't see your point. The downloads are indexed by the download indexer, so it should provide the API to access them. Why would we merge all of this together?
